spring:
  application:
    name: zq_sushuodorm_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.93.160:8085/
    username: zq_dorm
    password: Fyt)Tn3HdM2>vp}P*n8Do0


mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.ziqiang.sushuodorm.entity