wxapp:
  appId:
    abc
  appSecret:
    abc
  merchantId:
    abc
  merchantSerialNumber:
    abc
  merchantPrivateKey:
    abc
  apiV3Key:
    abc
  payNotifyUrl:
    abc

spring:
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://ziqiangpublic.mysql.rds.aliyuncs.com:3306/zq_wenchuang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    username:
      ziqiang_rds
    password:
      ziqiang_studio_mysql
  elasticsearch:
    rest:
      uris: 120.26.218.186:9200
  data:
    redis:
      host: 120.26.134.179
      port: 6379

mybatis-plus:
  mapper-locations: /mapper/*.xml